Fix URL generation for RSS
We have a bunch of 500 errors since URL like
https://badges.fedoraproject.org/user/misc?history_limit=42 generate
a link to user/misc?history_limit=42/rss, which in turn cause trouble
since 42/rss can't be turned into a int, generating a traceback:

    File "/usr/lib/python2.7/site-packages/pyramid/router.py", line 163, in handle_request
      response = view_callable(context, request)
    File "/usr/lib/python2.7/site-packages/pyramid/config/views.py", line 355, in rendered_view
      result = view(context, request)
    File "/usr/lib/python2.7/site-packages/pyramid/config/views.py", line 501, in _requestonly_view
      response = view(request)
    File "/usr/lib/python2.7/site-packages/tahrir/views.py", line 1042, in user
      history_limit = int(request.params.get('history_limit', 10))
  ValueError: invalid literal for int() with base 10: '42/rss'